# Generated by Django 3.2.4 on 2021-11-24 22:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbackground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackground',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='userbackground',
            name='generated_background',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Generated Background'),
        ),
    ]
