# Generated by Django 3.2.4 on 2021-11-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbackground', '0002_auto_20211124_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackground',
            name='company_logo',
            field=models.ImageField(max_length=140, upload_to='', verbose_name='Company Logo'),
        ),
    ]
